config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do 
    namespace :v1 do 
      get '/product_reviews/judgme_csv', to: 'product_reviews#judgme_csv'
    end 
  end 
  root to: 'admin/dashboard#index'
end

app/views/admin/suppliers_products_orders_management/_suppliers_products_orders_management.html.erb
<table class="index_table index">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product Name</th>
      <th>State</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <img class="col_image" src="<%= product.image_url %>"/>
      </td>
      <td>
        <%= product.name %>
      </td>
      <td>
        <%= product.state.humanize %>
      </td>
      <td>
        <button class="action-button">
          <a href="<%= admin_product_path(product.id) %>" target="_blank">Edit</a>
        </button>
      </td>
    </tr>
  </tbody>
</table>

<div class="section-title">
  <h1>Competition</h1>
  <div class="section-actions">
    <button class="action-button">
      <a href="<%= new_admin_competitor_product_intel_path %>" target="_blank">Add a competitor</a>
    </button>
  </div>
</div>
<table class="index_table index">
  <thead>
    <tr>
      <th>Image</th>
      <th>Source</th>
      <th>Name</th>
      <th>Item Location</th>
      <th>Sales Per Month</th>
      <th>Unit Price</th>
      <th>Shipping Fee</th>
      <th>Competition Score</th>
      <th>Demand Score</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%
      product.competitor_product_intels.each do |competitor|
    %>
      <tr>
        <td>
          <img class="col_image" src="<%= competitor.image_url %>">
        </td>
        <td><%= competitor.source %></td>
        <td><%= competitor.product.name %></td>
        <td><%= competitor.item_location %></td>
        <td><%= competitor.sales_per_month.round(2) %></td>
        <td><%= competitor.unit_price %></td>
        <td><%= competitor.shipping_price %></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>
          <a href="<%= admin_competitor_product_intel_path(competitor.id) %>" target="blank">Edit</a>
          <a href="<%= competitor.url %>" target="blank">Link</a>
        </td>
      </tr>
    <%
      end
    %>
  </tbody>
</table>

<div class="section-title">
  <h1>Suppliers</h1>
  <div class="section-actions">
    <button class="action-button">
      <a href="<%= admin_new_supplier_product_path(product_id: product.id) %>" target="_blank">Add a supplier</a>
    </button>
  </div>
</div>
<%
  product.supplier_products.each do |supplier_product|
%>
<section class="content-section">
  <table class="index_table index">
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><img class="col_image_small" src="<%= supplier_product.image_url %>"/></td>
        <td><%= supplier_product.supplier.name %></td>
        <td>
          <button class="action-button">
            <a href="<%= admin_supplier_product_path(supplier_product.id) %>" target="_blank">Edit the Supplier Product</a>
          </button>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="section-title">
    <h3>Quotes</h3>
    <div class="section-actions">
      <button class="action-button">
        <a href="<%= admin_new_supplier_product_quote_path(supplier_product_id: supplier_product.id) %>" target="_blank">Add a quote</a>
      </button>
    </div>
  </div>
  <table class="index_table index">
    <thead>
      <tr>
        <th>Conversation Reference</th>
        <th>Conversation Source</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Shipping Price</th>
        <th>Total Price</th>
        <th>Cost per Unit (USD)</th>
        <th>Cost per Unit (AUD)</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
  <%
    supplier_product.supplier_product_quotes.each do |quote|
  %>
      <tr>
        <td><%= quote.supplier_contact.reference_number %></td>
        <td><%= quote.supplier_contact.contact_type %></td>
        <td><%= quote.quantity %></td>
        <td><%= quote.unit_price %></td>
        <td><%= quote.shipping_price %></td>
        <td><%= quote.total_price %></td>
        <td><%= quote.cost_per_unit(currency_usd) %></td>
        <td><%= quote.cost_per_unit(currency_aud) %></td>
        <td><%= quote.state.humanize %></td>
        <td>
          <button class="action-button">
            <a href="<%= admin_supplier_product_quote_path(quote.id) %>" target="_blank">Edit the Quote</a>
          </button>
        </td>
      </tr>
  <%
    end
  %>
    </tbody>
  </table>
</section>
<%
  end
%>